name: 'Check Build'
on:
  push:
    branches:
      - master
      - dev
    paths:
      - 'src/**'
      - '.github/workflows/**'
      - 'package.json'
      - 'tsup.config.json'
  pull_request:
    branches:
      - master
      - dev
    paths:
      - 'src/**'
      - '.github/workflows/**'
      - 'package.json'
      - 'tsup.config.json'
jobs:
  build:
    runs-on: ubuntu-latest

    name: Node 16
    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - name: Setup NodeJS
        uses: actions/setup-node@v2
        with:
          node-version: 16
          registry-url: 'https://registry.npmjs.org'
          cache: 'npm'

      - name: Install dependencies
        run: npm i

      - name: Compile & Test
        run: npm test