name: "Publish Page"
on:
  push:
    branches:
      - master

jobs:
  publish_docs:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - name: Setup Node 16
        uses: actions/setup-node@v2
        with:
          node-version: 16
          registry-url: "https://registry.npmjs.org"

      - name: Install Dependencies
        run: npm i -D

      - name: TypeDoc
        run: npx typedoc src/index.ts
        env:
          npm_config_yes: true

      - name: Add CNAME, Publish
        run: |
          cd docs/
          touch CNAME
          echo 'heroku.js.org' > CNAME
          git init
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
          git add .
          git commit -am "Automated Docs"
          git branch -M gh-pages
          git remote add origin 'https://${{ secrets.GITHUB_TOKEN }}@github.com/Gary50613/herokuapi.js'
          git push origin gh-pages -f