name: "Publish Page"
on:
  push:
    branches:
      - master

jobs:
  publish_docs:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - name: Setup Node 16
        uses: actions/setup-node@v2
        with:
          node-version: 16
          registry-url: "https://registry.npmjs.org"

      - name: Install Dependencies
        run: npm i -D

      - name: TypeDoc
        run: npx typedoc src/index.ts
        env:
          npm_config_yes: true

      - name: Add CNAME, Publish
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs